// Writes src/domain/messages/grapheme-data.ts, the Unicode property table the SMS grapheme clusters are split with
// (src/domain/messages/graphemes.ts), from three files of the Unicode Character Database. Run it only to move the
// pinned Unicode version, and read docs/render-spec.md §12 first: a new version can move part boundaries and
// `characters`, so the golden files and the Java engine move with it.
//
//   npx tsx scripts/unicode-graphemes.ts <ucd-dir>
//
// <ucd-dir> holds, from https://www.unicode.org/Public/<version>/ucd/:
//   auxiliary/GraphemeBreakProperty.txt   Grapheme_Cluster_Break
//   emoji/emoji-data.txt                  Extended_Pictographic
//   DerivedCoreProperties.txt             Indic_Conjunct_Break (InCB)
// (flat in the folder or in those subfolders). Also copy auxiliary/GraphemeBreakTest.txt over
// src/domain/messages/GraphemeBreakTest.txt, and set UNICODE_VERSION in graphemes.ts.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

/** Grapheme_Cluster_Break values, in the order of the classes in graphemes.ts. */
const GCB = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"];
const INCB = ["None", "Linker", "Consonant", "Extend"];
const EXT_PICT = 16;
const INCB_SHIFT = 5;
const HANGUL_FIRST = 0xac00;
const HANGUL_LAST = 0xd7a3;

const dir = process.argv[2];
if (!dir) throw new Error("Usage: npx tsx scripts/unicode-graphemes.ts <ucd-dir>");

function read(name: string, sub: string): string {
  const flat = path.join(dir, name);
  return readFileSync(existsSync(flat) ? flat : path.join(dir, sub, name), "utf8");
}

/** Each data line's code point range and fields, comments dropped. */
function* entries(text: string): Generator<{ first: number; last: number; fields: string[] }> {
  for (const raw of text.split("\n")) {
    const line = raw.replace(/#.*/, "").trim();
    if (!line) continue;
    const [range, ...fields] = line.split(";").map((part) => part.trim());
    const [first, last = first] = range!.split("..").map((hex) => parseInt(hex, 16));
    yield { first: first!, last: last!, fields };
  }
}

/** The Unicode version in a file's header: "# GraphemeBreakProperty-17.0.0.txt", or emoji-data's "# Version: 17.0". */
function versionOf(text: string, file: string): string {
  const match = new RegExp(`${file}-(\\d+\\.\\d+)\\.\\d+\\.txt|^# Version: (\\d+\\.\\d+)$`, "m").exec(text);
  if (!match) throw new Error(`${file}: no version in its header`);
  return match[1] ?? match[2]!;
}

const gcbText = read("GraphemeBreakProperty.txt", "auxiliary");
const emojiText = read("emoji-data.txt", "emoji");
const coreText = read("DerivedCoreProperties.txt", "");
const version = versionOf(gcbText, "GraphemeBreakProperty");
for (const [text, file] of [
  [emojiText, "emoji-data"],
  [coreText, "DerivedCoreProperties"],
] as const) {
  if (versionOf(text, file) !== version) throw new Error(`${file} isn't Unicode ${version}`);
}
const fullVersion = /GraphemeBreakProperty-(\d+\.\d+\.\d+)\.txt/.exec(gcbText)![1]!;

const value = new Uint8Array(0x110000);
for (const { first, last, fields } of entries(gcbText)) {
  const gcb = GCB.indexOf(fields[0]!);
  if (gcb < 1) throw new Error(`Unknown Grapheme_Cluster_Break ${fields[0]}`);
  for (let cp = first; cp <= last; cp++) value[cp] = (value[cp]! & ~15) | gcb;
}
for (const { first, last, fields } of entries(emojiText)) {
  if (fields[0] !== "Extended_Pictographic") continue;
  for (let cp = first; cp <= last; cp++) value[cp]! |= EXT_PICT;
}
for (const { first, last, fields } of entries(coreText)) {
  if (fields[0] !== "InCB") continue;
  const incb = INCB.indexOf(fields[1]!);
  if (incb < 1) throw new Error(`Unknown InCB ${fields[1]}`);
  for (let cp = first; cp <= last; cp++) value[cp]! |= incb << INCB_SHIFT;
}

// Hangul syllables are computed, not stored: LV every 28th from U+AC00, LVT between. Check that the data says so.
for (let cp = HANGUL_FIRST; cp <= HANGUL_LAST; cp++) {
  const expected = GCB.indexOf((cp - HANGUL_FIRST) % 28 === 0 ? "LV" : "LVT");
  if (value[cp] !== expected) throw new Error(`U+${cp.toString(16)} isn't the LV/LVT the formula gives`);
  value[cp] = 0;
}

// Runs of equal value, as [start, value] where the value changes. Written as one string: per run, the distance
// from the previous start and the value, each in base 36, the distance ending in ":" and the value in ",".
let table = "";
let runs = 0;
let previousStart = 0;
let previousValue = 0;
for (let cp = 0; cp < value.length; cp++) {
  if (value[cp] === previousValue) continue;
  table += `${(cp - previousStart).toString(36)}:${value[cp]!.toString(36)},`;
  previousStart = cp;
  previousValue = value[cp]!;
  runs++;
}

const out = `// Generated by scripts/unicode-graphemes.ts from the Unicode Character Database ${fullVersion}. Don't edit by hand.
// For each run of code points with the same properties: how far it starts from the previous run (base 36), ":",
// then its properties (base 36), ",". The properties are a Grapheme_Cluster_Break class (the low 4 bits, in the
// order of graphemes.ts's classes), Extended_Pictographic (16) and the Indic_Conjunct_Break class times 32. Code
// points before the first run, and Hangul syllables (computed), are 0. ${runs} runs.

export const GRAPHEME_DATA_VERSION = "${fullVersion}";

export const GRAPHEME_DATA =
  ${JSON.stringify(table)};
`;
const target = path.join(import.meta.dirname, "..", "src", "domain", "messages", "grapheme-data.ts");
writeFileSync(target, out);
console.log(`Wrote ${path.relative(process.cwd(), target)}: Unicode ${fullVersion}, ${runs} runs, ${table.length} characters.`);
