// @vitest-environment happy-dom
import { act } from "react";
import { createRoot, type Root } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { SidebarProvider, SidebarTrigger, useSidebar } from "./sidebar";

// sidebar.tsx is generated by shadcn, edited on purpose: its window-level ⌘B / Ctrl+B listener is removed, because
// the editor's Bold uses the same keys. These tests catch a `shadcn add sidebar` that brings the listener back.

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

function Probe() {
  const { open } = useSidebar();
  return <span data-testid="open">{String(open)}</span>;
}

let root: Root;
let container: HTMLElement;

const openText = () => container.querySelector('[data-testid="open"]')?.textContent;
const sidebarCookie = () => document.cookie.split("; ").find((c) => c.startsWith("sidebar_state="));

function press(target: EventTarget, init: KeyboardEventInit) {
  const event = new KeyboardEvent("keydown", { key: "b", bubbles: true, cancelable: true, ...init });
  act(() => {
    target.dispatchEvent(event);
  });
  return event;
}

beforeEach(() => {
  document.cookie = "sidebar_state=; path=/; max-age=0";
  container = document.createElement("div");
  document.body.append(container);
  root = createRoot(container);
  act(() =>
    root.render(
      <SidebarProvider>
        <Probe />
        <SidebarTrigger />
      </SidebarProvider>,
    ),
  );
});
afterEach(() => {
  act(() => root.unmount());
  container.remove();
  document.cookie = "sidebar_state=; path=/; max-age=0";
});

describe("SidebarProvider keyboard", () => {
  it.each([
    ["⌘B", { metaKey: true }],
    ["Ctrl+B", { ctrlKey: true }],
  ])("%s on the window leaves the sidebar and its cookie alone", (_, init) => {
    const event = press(window, init);

    expect(openText()).toBe("true");
    expect(sidebarCookie()).toBeUndefined();
    expect(event.defaultPrevented).toBe(false);
  });

  it("⌘B in an editor that handles it as Bold doesn't reach the sidebar", () => {
    const editor = document.createElement("div");
    editor.contentEditable = "true";
    editor.addEventListener("keydown", (e) => e.preventDefault());
    container.append(editor);

    press(editor, { metaKey: true });

    expect(openText()).toBe("true");
    expect(sidebarCookie()).toBeUndefined();
  });

  it("the trigger still toggles the sidebar and keeps its cookie", () => {
    const trigger = container.querySelector<HTMLButtonElement>('[data-slot="sidebar-trigger"]')!;
    act(() => trigger.click());

    expect(openText()).toBe("false");
    expect(sidebarCookie()).toBe("sidebar_state=false");
  });
});
